version: '3'

services:
  order:
    image: gknguyen/order-service
    environment:
      - NODE_ENV=production
      - MONGODB_CONNECTION=mongodb+srv://root:root@firstcluster.idem7.mongodb.net/order_payment?authSource=admin&replicaSet=atlas-t8jym4-shard-0&readPreference=primary&appname=MongoDB%20Compass&ssl=true
    ports:
      - 4100:4000

  payment:
    image: gknguyen/payment-service
    environment:
      - NODE_ENV=production
      - MONGODB_CONNECTION=mongodb+srv://root:root@firstcluster.idem7.mongodb.net/order_payment?authSource=admin&replicaSet=atlas-t8jym4-shard-0&readPreference=primary&appname=MongoDB%20Compass&ssl=true
    ports:
      - 5100:5000
