version: '3'

services:
  order:
    image: gknguyen/order-service
    environment:
      - NODE_ENV=production
      - MYSQL_CONNECTION=mysql://root:@127.0.0.1:3306/order_payment
    ports:
      - 4100:4000

  payment:
    image: gknguyen/payment-service
    environment:
      - NODE_ENV=production
      - MYSQL_CONNECTION=mysql://root:@127.0.0.1:3306/order_payment
    ports:
      - 5100:5000
